/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as MatifoodRouteImport } from './routes/matifood'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatifoodProductsRouteImport } from './routes/matifood_.products'
import { Route as MatifoodAdminRouteImport } from './routes/matifood_.admin'

const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const MatifoodRoute = MatifoodRouteImport.update({
  id: '/matifood',
  path: '/matifood',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatifoodProductsRoute = MatifoodProductsRouteImport.update({
  id: '/matifood_/products',
  path: '/matifood/products',
  getParentRoute: () => rootRouteImport,
} as any)
const MatifoodAdminRoute = MatifoodAdminRouteImport.update({
  id: '/matifood_/admin',
  path: '/matifood/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/matifood': typeof MatifoodRoute
  '/operations': typeof OperationsRoute
  '/matifood/admin': typeof MatifoodAdminRoute
  '/matifood/products': typeof MatifoodProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/matifood': typeof MatifoodRoute
  '/operations': typeof OperationsRoute
  '/matifood/admin': typeof MatifoodAdminRoute
  '/matifood/products': typeof MatifoodProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/matifood': typeof MatifoodRoute
  '/operations': typeof OperationsRoute
  '/matifood_/admin': typeof MatifoodAdminRoute
  '/matifood_/products': typeof MatifoodProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/matifood'
    | '/operations'
    | '/matifood/admin'
    | '/matifood/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/matifood'
    | '/operations'
    | '/matifood/admin'
    | '/matifood/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/matifood'
    | '/operations'
    | '/matifood_/admin'
    | '/matifood_/products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  MatifoodRoute: typeof MatifoodRoute
  OperationsRoute: typeof OperationsRoute
  MatifoodAdminRoute: typeof MatifoodAdminRoute
  MatifoodProductsRoute: typeof MatifoodProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matifood': {
      id: '/matifood'
      path: '/matifood'
      fullPath: '/matifood'
      preLoaderRoute: typeof MatifoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matifood_/products': {
      id: '/matifood_/products'
      path: '/matifood/products'
      fullPath: '/matifood/products'
      preLoaderRoute: typeof MatifoodProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matifood_/admin': {
      id: '/matifood_/admin'
      path: '/matifood/admin'
      fullPath: '/matifood/admin'
      preLoaderRoute: typeof MatifoodAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  MatifoodRoute: MatifoodRoute,
  OperationsRoute: OperationsRoute,
  MatifoodAdminRoute: MatifoodAdminRoute,
  MatifoodProductsRoute: MatifoodProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
